# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DadosCenso
                                 A QGIS plugin
 baixa os setores dos censos do IBGE juntando com os resultados por setores escolhidos, os dados são baixados do https://ftp.ibge.gov.br/.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-07-19
        copyright            : (C) 2021 by Carlos Eduardo Cagna
        email                : carlos_cagna@yahoo.com.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DadosCenso class from file DadosCenso.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .dados_censo import DadosCenso
    return DadosCenso(iface)
